### ISSUE TITLE
Proposing changes to default configuration

### ISSUE THREAD

**Issue by kylecesmat** [FormidableLabs/eslint-config-formidable#8]
We can use this issue as a place to collect feedback on the current configuration of eslint-rules before being released@1.0

**Note from Roemer**: We're laserlight focused on getting `v1.0.0` out, so any issues getting bogged down in bikeshedding (particularly if code-style-only), will be captured in a post-`initial-release` issue with @kenwheeler making an interim executive decision for current release).

**Comment by kenwheeler** [comment]
So I'm a big fan of: 
- `react/no-multi-comp` - One component per file
- `react/sort-comp` - Ordering of lifecycle methods
- `react/sort-prop-types` - Alphabetical propTypes
- `react/no-string-refs` - Enforce functional refs

I feel like these would really put some polish on our react code.

**Comment by ryan-roemer** [comment]
@kenwheeler @kylecesmat -- Let's set a deadline on this and other `initial-release` issues (say EOD today), and then focus on releasing `v1.0`. Seems we don't have much uptick in convo's other than quotes bikeshedding, which is conveniently contained in a post-`v1.0` issue.

Sound good?

**Comment by kylecesmat** [comment]
@ryan-roemer sounds good, I'll jump on this right now and we'll get `1.0` out

**Comment by tptee** [comment]
Can we make `no-magic-numbers` a bit smarter? It's maddening to get this error when doing things like `indexOf` or using array indices when there's no array destructuring in node 4 code.

I think this would be adequate:
`no-magic-numbers: ["error", { "ignore": [-1, 0, 1] }]`

This is a bit heavy-handed to me, but it's another option:
`no-magic-numbers: ["error", { "ignoreArrayIndexes": true }]`

**Comment by bmathews** [comment]
+1 to `no-magic-numbers: ["error", { "ignore": [-1, 0, 1] }]`.

**Comment by chrisbolin** [comment]
our current linting doesn’t suggest which of these is preferred:

``` javascript
this.setState({ themeName });
this.setState({themeName});
```

**Comment by kylecesmat** [comment]
@chrisbolin my preference is the first example. We can add this with ~~http://eslint.org/docs/rules/space-in-brackets~~ http://eslint.org/docs/rules/object-curly-spacing

**Comment by kenwheeler** [comment]
@kylecesmat we'd probably want something like `"object-curly-spacing": ["error", "always"]`

**Comment by kylecesmat** [comment]
Yep - that's a better ruleset
